version: 2

aliases:
  - &working_directory
    ~/repo

  - &restore_cache
    keys:
    - dependencies-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - dependencies-

  - &npm_install
    name: npm dependencies
    command: npm install

  - &save_cache
    paths:
      - node_modules
    key: dependencies-{{ checksum "package.json" }}

defaults: &defaults
  docker:
    - image: circleci/node:latest

  working_directory: *working_directory

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Check versions
          command: |
            node --version
            npm --version
            docker --version

      # Download and cache dependencies
      - restore_cache: *restore_cache
      - run: *npm_install
      - save_cache: *save_cache

      - run:
          name: Build
          command: |
            npm run build

      - persist_to_workspace:
          root: *working_directory
          paths:
            - public

  test:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: .

      # Restore dependencies
      - restore_cache: *restore_cache

      - run:
          name: Check versions
          command: |
            node --version
            npm --version
            docker --version

      # Download and cache dependencies
      - restore_cache: *restore_cache
      - run: *npm_install
      - save_cache: *save_cache

      - run:
          name: Test
          command: |
            npm run test

  github-pages:
    <<: *defaults

    steps:
      - add_ssh_keys:
          fingerprints:
            - "68:db:30:72:2f:d5:da:67:92:65:2b:41:ed:c4:ff:27"

      - checkout

      - attach_workspace:
          at: .

      # Restore dependencies
      - restore_cache: *restore_cache

      - run:
          name: Check versions
          command: |
            node --version
            npm --version
            docker --version

      - run:
          name: Update GitHub Pages
          command: |
            git config --global user.email "no-reply@agid.gov.it"
            git config --global user.name "AGID deploy"
            npm run deploy

# Workflows enable multiple jobs in parallel
workflows:
  version: 2

  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages

      - test:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages

      - github-pages:
          requires:
            - test
          filters:
            branches:
              only: master
